"""add preview_url back

Revision ID: 5becc3c7c0b2
Revises: cd41a9387e01
Create Date: 2026-04-03 23:10:07.113236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5becc3c7c0b2'
down_revision = 'cd41a9387e01'
branch_labels = None
depends_on = None


def upgrade():
    # preview_url already added by 91754e3a6ecc — no-op
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('preview_url')

    op.create_table('user_song',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('song_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'song_id')
    )
    # ### end Alembic commands ###
