"""add online_source to song

Revision ID: 63662c6f276f
Revises: 
Create Date: 2026-03-22 22:38:40.704565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '63662c6f276f'
down_revision = None
branch_labels = None
depends_on = None





def upgrade():
    if not _has_column('song', 'online_source'):
        with op.batch_alter_table('song', schema=None) as batch_op:
            batch_op.add_column(sa.Column('online_source', sa.String(length=500), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('online_source')

    # ### end Alembic commands ###

def _has_column(table, column):
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    tables = inspector.get_table_names()
    if table not in tables:
        return False
    return column in [c['name'] for c in inspector.get_columns(table)]
